### ISSUE TITLE
设置了点击事件，点击事件抢了焦点，移动不了怎么解决

### ISSUE THREAD

**Issue by senlinxuefeng** [yueban/DraggedViewPager#2]
楼主，在设置item的点击事件后，点击事件抢了焦点，item移动不了怎么解决

**Comment by yueban** [comment]
@senlinxuefeng 抱歉，最近有些忙，周末我看一下再给你回复

**Comment by yueban** [comment]
@senlinxuefeng 我这边尝试了一下，发现并没有问题唉~~

**Comment by senlinxuefeng** [comment]
@yueban 不好意思啊，我设置到了itemView子view上了，出现了强焦点情况，我设置tag后，gettag得到却是page的位置，我看了您的源码，发现了在内部设置了tag，楼主我去掉settag后没有影响吧？

**Comment by yueban** [comment]
会有影响，代码中通过tag记录的子item的pageIndex。尝试为子View设置 android:descendantFocusability=“blocksDescendants" 锁定焦点

**Comment by senlinxuefeng** [comment]
非常感谢楼主的解答啊，我用另一种方法实现了，我在子view了settag，然后通过((LinearLayout)v).getChildAt(0).getTag()这种方式实现了需求，另外我们的项目里刚好用到你的库，由于项目的需求，最有一个page不能移动，并且item不能一道最后一个page里，首先我实现了最后一页的page不能移动，就是不知道怎么静止把item移动到最后一页，楼主可否帮一下

**Comment by senlinxuefeng** [comment]
@yueban 非常感谢楼主的解答啊，我用另一种方法实现了，我在子view了settag，然后通过((LinearLayout)v).getChildAt(0).getTag()这种方式实现了需求，另外我们的项目里刚好用到你的库，由于项目的需求，最有一个page不能移动，并且item不能一道最后一个page里，首先我实现了最后一页的page不能移动，就是不知道怎么静止把item移动到最后一页，楼主可否帮一下

**Comment by yueban** [comment]
1.你可以通过 setDragSetting 设置 page 是否可以被 拖拽 与 切换
2.page 禁止拖拽的情况下，item 也不会相应拖拽，控制逻辑你可以自己看一下，最近项目比较紧，可能抽不出时间添加功能
