### ISSUE TITLE
Performance Issues Quoted.

### ISSUE THREAD

**Issue by SriKrishnaCovalense** [yueban/DraggedViewPager#3]
Hi Yuben,

You have quoted performance issues f your project in another similar project (woxblom/DragListView) Link : https://github.com/woxblom/DragListView/issues/2#issuecomment-209706210

Are they fixed?
I am actually looking to use your library. Please guide.

**Comment by yueban** [comment]
Not yet. You can use [DragListView](https://github.com/woxblom/DragListView/) for good performance without page swipe. Or use my project with bad performance.I'm sorry having no time to optimize it recently.

**Comment by iRYO400** [comment]
Hi @yueban !
Can you please give tips about how did you implement drag'n'drop Cardviews between lists?
I tried to make with this https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf#.pebekt83m
but drag'n'drop works only inside of its parent

**Comment by yueban** [comment]
@iRYO400 refer to this article [drag-and-drop-with-animation-on-linearlayout](http://blog.zhanghai.me/drag-and-drop-with-animation-on-linearlayout/), it implements item swipe in vertical LinearLayout, but it's in Chinese

**Comment by SriKrishnaCovalense** [comment]
Thanks yueban :+1:

**Comment by yueban** [comment]
this repo has been deprecated. recommend https://github.com/woxblom/DragListView instead.
