### ISSUE TITLE
楼主，这个库还有维护么？

### ISSUE THREAD

**Issue by yuxingfafu** [yueban/DraggedViewPager#4]
楼主，这个库还有维护么？请教下就是动态设置每个也页面的行数和列数有入口么？类似launcher那种拖拽排序，可以指定行数和列数的。多谢：）

**Comment by yueban** [comment]
这个库已经不维护了，建议你使用 https://github.com/woxblom/DragListView

另外，这个库的实现是基于 LinearLayout 的，由于存在较频繁的 view create/destroy，性能很差。而 DragListView 则基于 RecyclerView 实现，性能好很多。另外，你需求的是类似 Launcher 的效果，也与 DragListView 所采用的 RecyclerView 更契合，毕竟从 list 转变为 grid，对于 RecyclerView 来说只是换了一个 LayoutManager。但是其中的实现细节还是以源码为准。

**Comment by yuxingfafu** [comment]
hao,多谢。我看看：）

**Comment by yuxingfafu** [comment]
楼主是否方便留个联系方式请教下的呀：）

**Comment by yueban** [comment]
就通过 github 账号联系好了

2019-07-08 16:54 GMT+08:00, fafuyuxing <notifications@github.com>:
